group: deprecated-2017Q2

branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9
      env: COMPONENT=iOS

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git BluePic-Server/Package-Builder
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/Testing-Credentials.git

script:
  - cd BluePic-Server && ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR -credentialsDir $TRAVIS_BUILD_DIR/Testing-Credentials/BluePic/ci
  - if [[ "$COMPONENT" == "iOS" ]]; then cd $TRAVIS_BUILD_DIR/BluePic-iOS; xcodebuild -workspace BluePic.xcworkspace/ -scheme BluePic -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO -quiet; fi
