
module: KituraBuddy
author: IBM
github_url: https://github.com/IBM-Swift/KituraBuddy

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraBuddy.xcodeproj, -target, KituraBuddy, LIBRARY_SEARCH_PATHS=.build/debug]
